config/routes.rb
Rails.application.routes.draw do
	root to: 'pages#index'
	resources :items, only: [:new, :create]
	resources :pins, only: [:create, :destroy]
	resources :users, only: [:index]
	resources :follows, only: [:create, :destroy]
    devise_for :users
  scope path: '/feeds', controller: :feeds, as: 'feed' do
	  # get 'user/:id', to: :user, as: :user
	  get 'me', to: :user
	  get 'flat', to: :flat
	  get 'aggregated', to: :aggregated
	  get 'notification', to: :notification
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
	belongs_to :user
belongs_to :target, class_name: "User"

validates :target_id, presence: true
validates :user_id, presence: true

include StreamRails::Activity
as_activity

def activity_notify
  [StreamRails.feed_manager.get_notification_feed(self.target_id)]
end

def activity_object
  self.target
end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user
belongs_to :item

validates :item, presence: true, uniqueness: {scope: :user}
validates :user, presence: true, uniqueness: {scope: :item}

include StreamRails::Activity
as_activity

def activity_object
  self.item
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :items
         has_many :follows

def followed_by(user = nil)
  user.follows.find_by(target_id: id)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
  # devise_parameter_sanitizer.for(:sign_up) << :name
end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
	before_action :authenticate_user!
  before_action :create_enricher

  def user
    @user = User.find(params[:id])
    feed = StreamRails.feed_manager.get_user_feed(@user.id)
    results = feed.get['results']
    @activities = @enricher.enrich_activities(results)
  end

  private

  def create_enricher
    @enricher = StreamRails::Enrich.new
  end

  def flat
  feed = StreamRails.feed_manager.get_news_feeds(current_user.id)[:flat]
  results = feed.get['results']
  @activities = @enricher.enrich_activities(results)
end

def aggregated
  feed = StreamRails.feed_manager.get_news_feeds(current_user.id)[:aggregated]
  results = feed.get['results']
  @activities = @enricher.enrich_aggregated_activities(results)
end

def notification
  feed = StreamRails.feed_manager.get_notification_feed(current_user.id)
  results = feed.get['results']
  @activities = @enricher.enrich_aggregated_activities(results)
end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
	before_action :authenticate_user!

  def create
    follow = Follow.new(follow_params)
    follow.user = current_user
    if follow.save
      StreamRails.feed_manager.follow_user(follow.user_id, follow.target_id)
    end
    flash[:success] = 'Followed!'
    redirect_to users_path
  end

  def destroy
    follow = Follow.find(params[:id])
    if follow.user_id == current_user.id
      follow.destroy!
      StreamRails.feed_manager.unfollow_user(follow.user_id, follow.target_id)
    end
    flash[:success] = 'Unfollowed!'
    redirect_to users_path
  end

  private

  def follow_params
    params.require(:follow).permit(:target_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user_id=current_user.id
    @item.save
    flash[:success] = "Item created!"
    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(:message, :title)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def index
  @items = Item.order('created_at DESC')
end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :authenticate_user!

  def create
    @pin = Pin.new(pin_params)
    @pin.user = current_user
    @pin.save!
    flash[:success] = "Pinned!"
    redirect_to root_path
  end

  def destroy
    @pin = Pin.find(params[:id])
    @pin.destroy
    flash[:success] = "Unpinned!"
    redirect_to root_path
  end

  private

  def pin_params
    params.require(:pin).permit(:item_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	 def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activity/_follow.html.erb
<div class="well well-sm">
  <p><small class="text-muted"><%= time_ago_in_words activity['time'] %> ago</small></p>

  <p><strong><%= activity['object'].name %></strong> and <strong><%= activity['actor'].name %></strong> are now friends</p>
</div>

app/views/activity/_pin.html.erb
<div class="well well-sm">
  <p><small class="text-muted"><%= time_ago_in_words activity['time'] %> ago</small></p>
  <p>
    <strong><%= activity['actor'].name %></strong> pinned
    <strong><%= activity['object'].title %></strong>
  </p>
</div>

app/views/aggregated_activity/_follow.html.erb
<i class="glyphicon glyphicon-time"></i> <%= time_ago_in_words(activity['updated_at']) %> ago

<% for activity in activity['activities'] %>
  <%= render_activity activity %>
<% end %>

app/views/aggregated_activity/_pin.html.erb
<% if activity['actor_count'] == 1 %>
  <%= activity['activities'][0]['actor'].name %> pinned <%= pluralize(activity['activity_count'], 'item') %>
<% elsif activity['actor_count'] == 2 %>
  <%= activity['activities'][0]['actor'].name %> and <%= activity['activities'][1]['actor'].name %> pinned <%= activity['activity_count'] %> items
<% else %>
  <%= activity['activities'][0]['actor'].name %>, <%= activity['activities'][1]['actor'].name %> and <%= activity['actor_count'].name - 2 %> more pinned <%= activity['activity_count'] %> items
<% end %>

<div class="pull-right">
  <i class="glyphicon glyphicon-time"></i> <%= time_ago_in_words(activity['updated_at']) %> ago
</div>

<% for activity in activity['activities'] %>
  <%= render_activity activity %>
<% end %>

app/views/feeds/aggregated.html.erb
<div class="page-header"><h1>Aggregated feed</h1></div>

<% for activity in @activities %>
  <%= render_activity activity %>
<% end %>

app/views/feeds/flat.html.erb
<div class="page-header"><h1>Flat feed</h1></div>

<% for activity in @activities %>
  <%= render_activity activity %>
<% end %>

app/views/feeds/notification.html.erb
<div class="page-header"><h1>Your notification feed</h1></div>

<% for activity in @activities %>
  <%= render_activity activity %>
<% end %>

app/views/feeds/user.html.erb
<div class="page-header"><h1>My feed</h1></div>

<% for activity in @activities %>
  <%= render_activity activity %>
<% end %>

app/views/items/_item.html.erb
<div class="well well-sm">
  <small class="text-muted"><%= time_ago_in_words item.created_at %> ago</small>
  <h3><%= item.title %></h3>
  <p><%= item.message %></p>

  <%= render "pins/form", item: item %>
</div>

app/views/items/new.html.erb
<div class="page-header"><h1>New item</h1></div>

<%= form_for @item do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :message %>
    <%= f.text_area :message, class: 'form-control' %>
  </div>

  <%= f.submit 'Create', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'FeedMe', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">

      </ul>
    </div>
  </div>
</nav>
  </head>

  <body>
  <div class="container">
  <ul class="nav navbar-nav">
  <% if user_signed_in? %>
    <li>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="glyphicon"></i> <%= current_user.name %><b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to 'Users', users_path %></li>
        <li><%= link_to 'Flat feed', feed_flat_path %></li>
<li><%= link_to 'Aggregated feed', feed_aggregated_path %></li>
<li><%= link_to 'Notification feed', feed_notification_path %></li>
      </ul>
    </li>
  <% end %>
</ul>

  <%= yield %>
</div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="page-header"><h1>Welcome!</h1></div>

<%= render @items %>

app/views/users/_user.html.erb
<h3><%= user.name %></h3>

<h3><%= link_to user.name, feed_user_path(user) %></h3>

<% if user.followed_by(current_user) %>
  <%= button_to "Unfollow", follow_path(user.followed_by(current_user)), method: :delete, :class => "btn btn-primary btn-sm btn-danger" %>
<% else %>
  <%= form_for :follow, url: follows_path do |f| %>
    <%= f.hidden_field :target_id, value: user.id %>
    <input class="btn btn-primary btn-sm btn-default" type="submit" value="Follow">
  <% end %>
<% end %>

app/views/users/index.html.erb
<div class="page-header"><h1>Users</h1></div>

<%= render @users %>